version: '2'

services:
  etcd:
    image: docker.io/bitnami/etcd:3-debian-10
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - ~/docker/etcd3/data:/bitnami/etcd
    ports:
    - 2379:2379
    - 2380:2380